# Generated by Django 4.0.5 on 2022-06-04 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e2a2c99-d01c-462d-ba19-c11c6ea1dd96'), editable=False, primary_key=True, serialize=False),
        ),
    ]
