# Generated by Django 4.0.5 on 2022-06-06 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e74deb15-cf1b-448a-826e-4cfa00354d77'), editable=False, primary_key=True, serialize=False),
        ),
    ]
