# Generated by Django 4.0.5 on 2022-06-06 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b86a99ac-7649-4d13-bbe6-fcefa062000f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
